version: '3.7'

services:
  db:
    build: ./database/.
    container_name: postgres
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_pwd
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"

  app:
    build: "."
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - environment.env
    expose:
      - "8080"
    ports:
      - "8080:8080"

  mock:
    image: mockserver/mockserver
    ports:
      - "1080:1080"

  # keycloak:
  #   build: "./keycloak"
  #   command: ["start-dev", "--http-port 8081"]
  #   depends_on:
  #     - db
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
  #   environment:
  #     - KC_DB=postgres
  #     - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
  #     - KC_DB_USERNAME=my_user
  #     - KC_DB_PASSWORD=my_pwd
  #     - KC_HOSTNAME=localhost
  #     - KC_HOSTNAME_PORT=8081
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
