version: '3.7'

services:
  db:
    build: ./database/.
    container_name: postgres
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_pwd
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"

  app:
    build: "."
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/home/node/app/src
    expose:
      - "8080"
    ports:
      - "8080:8080"