import { DataSource } from "typeorm";
import { 
    Account, 
    Device, 
    Profile, 
    ProfileDevice,
    PillRoutine,
    PillRoutineStatus,
    PillRoutineStatusEvent,
    PillRoutineType,
    ModifiedPillStatus,
    ModifiedPill,
    ModifiedPillStatusEvent,
    PillReeschadule,
    PillRoutineVersion,
} from "./models";

export const AppDataSource = new DataSource({
    type: "postgres",
    host: process.env.MEDICINE_API_DB_HOST,
    port: process.env.MEDICINE_API_DB_PORT,
    username: process.env.MEDICINE_API_DB_USER,
    password: process.env.MEDICINE_API_DB_PASS,
    database: process.env.MEDICINE_API_DB_NAME,
    synchronize: false,
    logging: false,
    entities: [
        Account, 
        Profile,
        Device,
        ProfileDevice,
        PillRoutine,
        PillRoutineStatus,
        PillRoutineStatusEvent,
        PillRoutineType,
        ModifiedPillStatus,
        ModifiedPill,
        ModifiedPillStatusEvent,
        PillReeschadule,
        PillRoutineVersion,
    ],
});
